# Generated by Django 3.1.7 on 2021-05-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_priority',
            field=models.IntegerField(default=50),
        ),
    ]
