# Generated by Django 3.2 on 2021-05-05 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.UUID('adc0dc83-8ffc-4819-b428-89795601df64'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('e7c39a9a-1a73-48de-851d-ec0aecaeef3d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
