# Generated by Django 3.2 on 2021-05-05 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210505_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.UUID('e2a8dc51-a1c2-4f45-8833-e74683a47562'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('7a81e7fb-7c87-447e-b25b-0e54a2cf81c9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
