# Generated by Django 3.2 on 2021-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210506_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
