# Generated by Django 3.2 on 2021-05-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210507_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
