# Generated by Django 3.1.7 on 2021-05-03 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=30)),
                ('channel_priority', models.IntegerField(default=50)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.UUID('b5110ce3-91d8-4170-9e8a-1366c8efbd17'), editable=False, primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=30)),
                ('post_priority', models.IntegerField(default=50)),
                ('post_content', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_channel.channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.UUID('81e7cc6f-18c4-44b8-9394-4705b50bd508'), editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_channel.post')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAdminGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_channel.channel')),
            ],
        ),
    ]
