# Generated by Django 3.2 on 2021-05-04 03:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=uuid.UUID('e1958983-92ae-44e0-ad3b-87beee83c26b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('d6162ef4-ea75-40ad-be87-315a9c3876f9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
